Repository 47degrees/github4s, pull requests merged in 2021-09, with the labels that each got.

#683 Update branch and compare commits
  github4s/src/main/scala/github4s/Decoders.scala
  github4s/src/main/scala/github4s/Encoders.scala
  github4s/src/main/scala/github4s/algebras/PullRequests.scala
  github4s/src/main/scala/github4s/algebras/Repositories.scala
  github4s/src/main/scala/github4s/domain/PullRequest.scala
  github4s/src/main/scala/github4s/domain/Repository.scala
  github4s/src/main/scala/github4s/interpreters/PullRequestsInterpreter.scala
  github4s/src/main/scala/github4s/interpreters/RepositoriesInterpreter.scala
  github4s/src/test/scala-2/github4s/unit/EncoderDecoderSpec.scala
  github4s/src/test/scala/github4s/integration/PullRequestsSpec.scala
  github4s/src/test/scala/github4s/integration/ReposSpec.scala
  github4s/src/test/scala/github4s/unit/PullRequestsSpec.scala
  github4s/src/test/scala/github4s/unit/ReposSpec.scala
  github4s/src/test/scala/github4s/utils/TestData.scala
  microsite/docs/pull_request.md
  microsite/docs/repository.md
Labels: enhancement

#690 Handle `default_branch` and `topics` in Repository
  github4s/src/main/scala/github4s/Decoders.scala
  github4s/src/main/scala/github4s/Encoders.scala
  github4s/src/main/scala/github4s/domain/Repository.scala
  github4s/src/test/scala/github4s/utils/FakeResponses.scala
  github4s/src/test/scala/github4s/utils/TestData.scala
Labels: breaking-change

#691 Fixes code formatting issue
  github4s/src/main/scala/github4s/Decoders.scala
  github4s/src/main/scala/github4s/algebras/GitData.scala
  github4s/src/main/scala/github4s/algebras/Repositories.scala
  github4s/src/test/scala/github4s/integration/PullRequestsSpec.scala
  github4s/src/test/scala/github4s/unit/ReposSpec.scala
  github4s/src/test/scala/github4s/utils/TestData.scala
  microsite/docs/activity.md
  microsite/docs/auth.md
  microsite/docs/contributing.md
  microsite/docs/docs.md
  microsite/docs/gist.md
  microsite/docs/git_data.md
  microsite/docs/issue.md
  microsite/docs/organization.md
  microsite/docs/project.md
  microsite/docs/pull_request.md
  microsite/docs/repository.md
  microsite/docs/team.md
  microsite/docs/user.md
  project/ProjectPlugin.scala
Labels: bug

#702 Re-enable scalajs support
  build.sbt
  project/plugins.sbt
Labels: enhancement
